repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.7.0  # be careful updating this - last attempt (to v1.19) broke alpine.js components
  hooks:
  - id: djlint-django
    args:
      - "--reformat"
      - "--quiet"
