# Generated by Django 4.1.7 on 2023-03-16 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the player", max_length=120
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key, used in URLs and code references",
                        max_length=120,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerAttributes",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        help_text="The player whose attributes these are",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="players.player",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Goal keeper"),
                            ("LB", "Left back"),
                            ("CB", "Centre back"),
                            ("RB", "Right back"),
                            ("DM", "Defensive midfield"),
                            ("CM", "Central midfield"),
                            ("AM", "Attacking midfield"),
                            ("LW", "Left winger"),
                            ("RW", "Right winger"),
                            ("ST", "Striker"),
                        ],
                        help_text="The player's primary position",
                        max_length=2,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        help_text="The player's current nationality", max_length=64
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        help_text="The current age of the player"
                    ),
                ),
                (
                    "score_defence",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="The player's defensive score, out of 100",
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "score_midfield",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="The player's midfield score, out of 100",
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "score_offence",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="The player's attacking score, out of 100",
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which the contract is valid"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="The length of the contract, in years"
                    ),
                ),
                (
                    "terms",
                    models.TextField(help_text="The agreed terms in the contract"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="The player signing the contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
