name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Run tests
        run: tox -f py$(echo ${{ matrix.python }} | tr -d .)
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: '.coverage.*'
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install --upgrade coverage
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-data
      - name: Generate coverage
        run: |
          python -m coverage combine
          python -m coverage html
          python -m coverage report --fail-under=100 --show-missing
      - name: Upload coverage
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: htmlcov